### GET test get router
GET http://localhost:8080/user/index?id=1

### GET test get router
GET http://localhost:8080/user/login

### DELETE test delete router
DELETE http://localhost:8080/user/name

### PUT test put router
PUT http://localhost:8080/user/name

### POST test post router
POST http://localhost:8080/user/index1
Content-Type: application/x-www-form-urlencoded


### POST test post router
POST http://localhost:8080/user/index2
Content-Type: application/x-www-form-urlencoded

id=1&id=2

### POST test post GetFormArrayQuery
POST http://localhost:8080/user/index3
Content-Type: application/x-www-form-urlencoded

user[id]=1&user[id]=2&user[name]="amie"

### POST test post BindJson
POST http://localhost:8080/user/index2
Content-Type: application/json

{
  "name": "amie",
  "age": 1,
  "password": "2145"
}
### POST test BindJson
POST http://localhost:8080/user/index2
Content-Type: application/json

[
  {
    "name": "amie3",
    "age": 20,
    "password": "2145"
  },
  {
    "name": "amie2",
    "age": 20,
    "password": "2145"
  }
]

### POST test BindXml
POST http://localhost:8080/user/index1
Content-Type: application/xml

<User>
    <name>张三</name>
    <age>20</age>
</User>